# Generated by Django 3.2.8 on 2021-11-02 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dictionary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=50)),
                ('phonetics', models.JSONField(default=list)),
                ('meanings', models.JSONField(default=list)),
                ('created_in', models.CharField(default='PostgreSQL', max_length=50)),
            ],
        ),
    ]
